### PR TITLE
trying again to update jmavlib

### PR DESCRIPTION
**Pull request by lovettchris**

### CODE REVIEW

**Comment by lovettchris** [comment]
sigh... how did the BOM com back ?  I have one more idea....

**Comment by LorenzMeier** [comment]
Hey, what's missing here?

**Comment by lovettchris** [comment]
One of the files I changed has a Unicode byte order mark at the top of the file (0xFF FE) and apparently your build system can't handle that kind of byte order mark.  But when I remove this in a branch and try and do a pull request "git" decides NOT to remove the byte order mark in the master branch.  So I believe this will require someone manually merging the bits and removing the byte order mark before committing to the master branch.   See https://en.wikipedia.org/wiki/Byte_order_mark.

**Comment by julianoes** [comment]
Replaced by #65, closing.

**Pull request closed without merging**
