### PR TITLE
Updating common.xml message definitions to mavlink 2.0

### PR DESCRIPTION
**Pull request by catch-twenty-two**
This along with an update to the jMAVLib allows jMAVSim to receive mavlink 2.0 messages.

Note: For this to PR work,[ this pull request](https://github.com/PX4/jMAVlib/pull/3) will need to be accepted and the resulting hash will need to be updated on this repo and committed.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@catch-twenty-two @clovett Are you interested to complete this?

**Comment by lovettchris** [comment]
Sure but what is to complete?  My pull request was merged, and this is just updating common.xml to the latest.  Do you need some testing perhaps?

**Comment by mhkabir** [comment]
@lovettchris It would be great to get jMAVSim working fully with MAVLink 2.0. I hacked it work, however that isn't a solution. 
Do you know what else is missing to get it working ?

**Comment by lovettchris** [comment]
I see, well jMavSim had a version of mavlink 1 ported to Java, I guess it will need a full Java port of [mavlink 2](https://github.com/mavlink/c_library_v2/tree/2faa6d49834aa203e2a3eeeeed588728fb14c431).  This would be some work then...

**Comment by julianoes** [comment]
There is also the Java generator in pymavlink that got some mavlink 2 support now: https://github.com/mavlink/pymavlink/pull/3.
Not sure how much work it would be to port jMAVSim to use the generated Java mavlink implementation.

**Comment by julianoes** [comment]
Replaced by #65, closing.

**Pull request closed without merging**
