### PR TITLE
simulate PX4FLOW sensor by producing HIL_OPTICAL_FLOW (WIP)

### PR DESCRIPTION
**Pull request by v01d**
This is only sonar at the moment. I first compute ground distance (by compensating for pitch/roll, as in Pixhawk code) and from that I simulate PX4FLOW's sonar range (0.3-4.0m). 

I expect flow to be simulated by computing vehicle's velocity and converting that to pixels. However, I haven't thought of the math yet. Also, maybe it would be interesting to condition valid flow to some maximum angle, distance, velocity, etc.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Hey - where are you standing with this? We've fixed a number of bugs in the INAV processing of flow data and also have an updated flow binary.

**Comment by v01d** [comment]
I'm not sure I can invest efforts in this at the moment. I must stay jmavsim is quite problematic sometimes and it looks like there's an effort to go with gazebo for SITL (which I understand would more easily support something like this). Maybe it is better to concentrate on that?

**Comment by LorenzMeier** [comment]
@v01d I have this now fully implemented in Gazebo - did you continue with this? @bugobliterator The simulation in Gazebo is better (it does actual optical flow on the actual camera image, so you get varying quality with varying surfaces), but if its unbearably slow you could consider using a jMAVSim based variant.

**Comment by v01d** [comment]
Hi, sorry, no, I haven't continued with this.

**Pull request closed without merging**
