### PR TITLE
Fix problems with HITL mode simulation with Pixhawk running latest PX4

### PR DESCRIPTION
**Pull request by lovettchris**
Latest PX4 px4fmu-v2 bits on Pixhawk, with a real radio control had weird problems flying crazy.  With these fixes it now flies smooth as silk.  Also tested SITL mode with QGC flying a mission, and it also works nicely.

### CODE REVIEW

**Comment by bkueng** [comment]
The HIL_STATE_QUATERNION serves as ground truth in SITL. Can you please test #44 instead? It should fix your problems.

**Comment by LorenzMeier** [comment]
I'm closing this PR in favour of #44.

**Comment by lovettchris** [comment]
an you explain the architecture of simulation someplace?  Because to me the low level HIL_SENSOR tells the PX4 what is really happening, the Position Estimator then publishes vehicle_attitude.  If you then turn around and have the simulator send HIL_STATE_QUATERNION then the PX4 mavlink receiver publishes another vehicle_attitude which could conflict with the position estimator, and it think this is causing crazy flying.  Isn't sending HIL_STATE_QUATERNION kind of cheeting?  The PX4 should react to new vectors computed from accelerometer, gyro data only.  It get's ground truth on GPS position, but sending "truth" of drone attitude is cheating.  It's like flying with a optitrack camera system, and I believe that the PX4 higher level modules will get confused if they see big discontinuous jumps in vehicle_attitude messages which can happen if they are coming from two different places.  It is also currently inefficient because HIL_STATE_QUATERNION also overlaps with HIL_SENSORS on the accel data.  It also overlaps with HIL_GPS.  Notice PX4 is expecting HIL_STATE_QUATERNION to send global position, and I'm not sure what happens when jmavsim doesn't fill in these fields of the message.  This may explain why I sometimes see the map jump back and forth between 0,0,0 and the real GPS location.
To me it makes sense to only send additional sensor data that is missing from HIL_SENSORS, like airspeed.

**Comment by bkueng** [comment]
Can you please try again or describe your exact setup. Because  #44 does the same thing as your changes here in HITL: it disables HIL_STATE_QUATERNION in HITL and only enables it in SITL. It works for me, I tested without any additional input connected.

You are right that in HITL we must not send HIL_STATE_QUATERNION as it would interfer with other stuff (which is the crazy thing that you experience :).

We send HIL_STATE_QUATERNION in SITL as ground truth, published in [0], and then it's just logged, but not further used in the system (and we only care about the attitude, which is why we don't set GPS and the other fields). True, it would be cheating if we used it :)

I only tested HITL yesterday for the first time, so I hope this makes sense.

For the climbing on arm problem, @julianoes is working on a proper fix.

[0] https://github.com/PX4/Firmware/blob/4b6441df0274541a0aa4c9153902e8361003afbb/src/modules/simulator/simulator_mavlink.cpp#L331

**Comment by julianoes** [comment]
For the climbing problems, @bkueng and I came up with: https://github.com/PX4/Firmware/pull/5716.

**Comment by sytelus** [comment]
Hi,
I'm still wondering why we want to publish HIL_STATE_QUATERNION to autopilot either in HIL or SITL. In both modes, autopilot should never know the ground truth for the good simulation. Shouldn't autopilot just receive sensor messages and estimate pose? If it knows ground truth then we want see the impact of noise in sensors or missing sensors, for example. Let me ask this question in other way: If we don't send HIL_STATE_QUATERNION to autopilot, what problems would we see?

**Pull request closed without merging**
