### PR TITLE
Update to latest jMAVlib

### PR DESCRIPTION
**Pull request by clovett**
Pick up the jMAVlib fix - support mavlink "extensions".  This stops lots of bad crc errors from spewing when receiving the old style (non-extended) SERVO_OUTPUT_RAW messages from PX4.  The SERVO_OUTPUT_RAW uses <extensions/> element which jMAVlib can now handle correctly.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Can you look into the CI failure?

**Comment by clovett** [comment]
Looks like the sort method I used on the list of fields only works on JDK 7, and not JDK 8... I'll look into finding another solution that works on older JDK versions.  But first I have to figure out how to get JDK7, the oracle web site says version 7 is only available to "Oracle customers"...

**Comment by LorenzMeier** [comment]
The alternative would be to update the build system.

**Comment by clovett** [comment]
sure, if you don't care about supporting JDK 7 any more... I've never messed with the continuous integration stuff before, is there a wiki I can read?

**Comment by LorenzMeier** [comment]
Can you figure out what the JDK version on Ubuntu 14.04 is? The versions are set here:
https://github.com/PX4/jMAVSim/blob/master/.travis.yml#L8

I would be ok to have openjdk8 and oraclejdk8 if 14.04 is on 8 already.

**Comment by LorenzMeier** [comment]
Can you rebase this now and reference the newer jMAVLib?

**Pull request closed without merging**
