### PR TITLE
Usability/functionality improvements/additions

### PR DESCRIPTION
**Pull request by mpaperno**
Seeing as this is the most active fork, maybe you guys are interested in these updates.  There's quite a few here together so perhaps someone would prefer to cherry pick some commits instead.  However all defaults have been preserved, and the only thing that would be wrong is the URL of the repo in the README (I wish GH had a way to insert variables).  I'm actively using this code and everything seems to work.  

If not interested, or merging changes otherwise, please close this PR.

This started with DrTon's current version and then merged forks from PX4 and @dlbd .  Then I brought over changes from my working copy which I've made over the last several months.

I'm using Windows primarily, so possibly some of the fixes are Win-specific, like being able to switch views with keyboard commands and getting the proper textures to load on the 3D model. 

I'd like to figure out how to use keyboard commands directly in the visualizer window (focus has to be in console now) and w/out having to hit Enter after each one.

Cheers,
-Max

### CODE REVIEW

**Comment by mpaperno** [comment]
PS. for PX4 serial connection you'd now need to add `-ap px4` to the command line. See e6c79e7 .

-Max

**Comment by LorenzMeier** [comment]
Thanks! We've removed the serial connectivity requirement since, so it should work out of the box. We'll need a couple of days to validate, but we're certainly interested in working with you guys in improving this.

**Comment by LorenzMeier** [comment]
@mpaperno Being able to switch views from the GUI would be very high on my wanted list. The console input is not useful for us at all.

**Comment by mpaperno** [comment]
Lorenz, sounds good, no rush (though I might keep fixing stuff if I find it :) ).  Yea would be nice if the visualizer window accepted key commands, but I'm not sure what's involved.  The console is awkward (less so with multiple monitors I suppose) but at least better than nothing for now.  After is starts i just click back in the console window and it's ready to accept key commands.  A startup option to set the initial view might be useful also.

-Max

**Comment by mpaperno** [comment]
@LorenzMeier Here you go! So much better.

**Comment by mpaperno** [comment]
Sim is looking pretty different these days...

jmavsim_apr_1_ground

You wanted key commands?  You got 'em!

```
Key commands (in the visualizer window):

Views:
    F    - First-person-view camera.
    S    - Stationary ground camera.
    G    - Gimbal camera.
    Z    - Toggle auto-zoom for Stationary camera.
   +/-   - Zoom in/out
 0/ENTER - Reset zoom to default.

Actions:
   Q   - Disable sim on MAV.
   I   - Enable sim on MAV.
   H   - Toggle HUD overlay.
   C   - Clear all messages on HUD.
   R   - Toggle data report sidebar.
   T   - Toggle data report updates.
   F1  - Show this key commands reference.
  ESC  - Exit jMAVSim.
 SPACE - Reset vehicle & view to start position.

Manipulate Vehicle:
  ARROW KEYS      - Rotate around pitch/roll.
  END/PG-DN       - Rotate CCW/CW around yaw.
  SHIFT + ARROWS  - Move N/S/E/W.
  SHIFT + INS/DEL - Move Up/Down.
  NUMPAD 8/2/4/6  - Start/increase rotation rate around pitch/roll
  NUMPAD 1/3      - Start/increase rotation rate around yaw axis.
  NUMPAD 5        - Stop all rotation.
  CTRL + NUMPAD 5 - Reset vehicle attitude, velocity, & accellerati

Manipulate Environment:
 ALT +
  ARROW KEYS      - Increase wind deviation in N/S/E/W direction.
  INS/DEL         - Increase wind deviation in Up/Down direction.
  NUMPAD 8/2/4/6  - Increase wind speed in N/S/E/W direction.
  NUMPAD 7/1      - Increase wind speed in Up/Down direction.
  NUMPAD 5        - Stop all wind and deviations.

 CTRL+ Manipulate - Rotate/move/increase at a higher/faster rate.
```
jmavsim_apr_1_fpv

jmavsim_apr_1_sky

So do you want me to keep this PR open indefinitely or...?   ;-)

Cheers,
-Max

**Comment by LorenzMeier** [comment]
Ugh, fantastic! Of course I'll get this in.

**Comment by mpaperno** [comment]
I should probably point out, since it's buried in all the commits... I added a "reset" flag to the `HIL_SENSOR` `fields_updated` bitfield, to let the autopilot know that the simulation has been reset.  It is set when one hits the SPACE bar in the sim.  In my use case, this resets the onboard UKF back to defaults (otherwise it may get confused about the sudden attitude/position change). 

https://github.com/PX4/jMAVSim/pull/20/commits/a897457e3a294651cd20140f0c49a173642b4cdd#diff-8b8d489c12560ab9c476a1f4c02239ceR125

Perhaps this is something useful to add to the official HIL_SENSOR message spec?

-Max

**Comment by LorenzMeier** [comment]
Can you send a PR against the MAVLink repo for that?

**Comment by mpaperno** [comment]
I'll take that as a :+1:.   Here you go... https://github.com/mavlink/mavlink/pull/534

But could you also do me a favor and merge this one?  https://github.com/mavlink/mavlink/pull/517

Thanks,
-Max

**Comment by mpaperno** [comment]
I also started a little wishlist for improvements...  https://github.com/mpaperno/jMAVSim/wiki/Wishlist

**Comment by catch-twenty-two** [comment]
@mpaperno wow, nice :+1:

**Pull request merged**
