### PR TITLE
Fix HITL simulation

### PR DESCRIPTION
**Pull request by bkueng**
By not publising HIL_STATE_QUATERNION by default.

fyi @mpaperno @kd0aij

### CODE REVIEW

**Comment by kd0aij** [comment]
@bkueng Does this break SITL for me? How do I get the same behavior I had before?

**Comment by bkueng** [comment]
It shouldn't. The required changed on FW side are in https://github.com/PX4/Firmware/pull/5706

**Comment by mpaperno** [comment]
:+1:

**Comment by LorenzMeier** [comment]
PX4 changes are in.

**Pull request merged**
